version: "3.8"

services:
  db:
    container_name: "db"
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: greenforum-backend
    image: 694201337911/greenforum-api 
    environment:
      TEST: "test"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
    ports:
      - "4000:4000"
    depends_on: 
      - db
    env_file:
      - ./.env
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
